/*CREATE TABLE ANGENTI(Cod_acent tinyint primary key,
Nume_agent varchar(20) not null,
Data_angajare date,
Data_nasterii date,
Functia varchar(20), 
Codfirma tinyint,
FOREIGN KEY (Codfirma) REFERENCES FIRME(CODFIRMA))
							
							
ADTER TABLE ANGENTI
ADD FOREIGN KEY (Codfirma)	
REFERENCES FIRME(CODFIRMA)


ALTER TABLE FIRME
ADD CONSTRAINT CK_ZONA CHECK (ZONA IN ('CENTRU', 'NORD', 'SUD'))
CREATE TABLE FOSTI_AGENTI AS
SELECT Cod_acent, Nume_agent, Functia, Codfirma
FROM angenti


ALTER TABLE ANGENTI RENAME personal


ALTER TABLE personal
ADD COLUMN (EMAIL VARCHAR(20))
ALTER TABLE personal
ADD COLUMN (VIRSTA TINYINT CHECK (VIRSTA>18))


INSERT INTO PERSONAL
VALUES (106, 'MACOVEI','2010-02-12','1990-10-22', 
				'AGENT', 10, 20  )
				
INSERT INTO personal (Cod_acent, Nume_agent, Codfirma, VIRSTA)
VALUES (101, 'Moscalu', 11, 21)


ALTER TABLE PERSONAL
MODIFY COLUMN EMAIL varchar(40)


ALTER TABLE personal
DROP COLUMN EMAIL


ALTER TABLE personal
ADD CHECK (VIRSTA>20);


ALTER TABLE PERSONAL
 DROP CHECK CKVIRSTA
 
 
 DROP TABLE FOSTI_AGENTI
 
 
 DELETE FROM personal
 
 
 -- DESCRIBE personal
 
 
 CREATE table salariati as
 SELECT *
 FROM personal;
 
 
 CREATE table salariati as
 SELECT *
 FROM personal
 WHERE 1=0;
 
 
 CREATE TABLE salariati_1 LIKE personal;
INSERT salariati(
SELECT *
FROM personal)	
 salariati
 
 
 SELECT *
 FROM personal
 
 
 INSERT INTO salariati_1
 (SELECT *
 FROM personal
 WHERE codfirma=10);
 

CREATE TABLE `salariati_2`
(
`ID_ANGAJAT` DECIMAL(10,0) NOT NULL,
`PRENUME` VARCHAR(20) NULL DEFAULT NULL,
`NUME` VARCHAR(25) NULL DEFAULT NULL,
`EMAIL` VARCHAR(25) NULL DEFAULT NULL,
`TELEFON` VARCHAR(20) NULL DEFAULT NULL,
`DATA_ANGAJARE` DATE NULL DEFAULT NULL,
`ID_FUNCTIE` VARCHAR(10) NULL DEFAULT NULL,
`SALARIUL` DECIMAL(10,0) NULL DEFAULT NULL,
`COMISION` DECIMAL(10,0) NULL DEFAULT NULL,
`ID_MANAGER` DECIMAL(10,0) NULL DEFAULT NULL,
`ID_DEPARTAMENT` DECIMAL(10,0) NULL DEFAULT NULL
)


SELECT PRENUME, NUME, SALARIUL, SALARIUL+100 as 'Salariu marit'     -- Din compainie
	from salariati_2
	WHERE SALARIUL<3000;
	
	
	updata salariati_2
	SET salariul = (SELECT salariul FROM salariul_2 WHERE ID_ANGAJAT = 125)

	CREATE TABLE `salariati_1`(
	`ID_ANGAJAT` DECIMAL(10,0) NOT NULL,
`PRENUME` VARCHAR(20) NULL DEFAULT NULL,
`NUME` VARCHAR(25) NULL DEFAULT NULL,
`EMAIL` VARCHAR(25) NULL DEFAULT NULL,
`TELEFON` VARCHAR(20) NULL DEFAULT NULL,
`DATA_ANGAJARE` DATE NULL DEFAULT NULL,
`ID_FUNCTIE` VARCHAR(10) NULL DEFAULT NULL,
`SALARIUL` DECIMAL(10,0) NULL DEFAULT NULL,
`COMISION` DECIMAL(10,0) NULL DEFAULT NULL,
`ID_MANAGER` DECIMAL(10,0) NULL DEFAULT NULL,
`ID_DEPARTAMENT` DECIMAL(10,0) NULL DEFAULT NULL)


DELETE
FROM salariati_1
WHERE ID_ANGAJAT=122 OR ID_ANGAJAT=123



DELETE
from salariati_1
WHERE ID_ANGAJAT IN (122 ,123)


DELETE
FROM salariati_1
WHERE YEAR(DATA_ANGAJARE)<2016


DELETE
FROM salariati_1
WHERE DATA_ANGAJARE LIKE '%2017%'*/